# Generated by Django 3.1.7 on 2021-03-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_cli', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id_ind', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('id_cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_clint_industry', to='api.client')),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id_ins', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('type_instruments', models.IntegerField(choices=[(1, 'Vávula'), (2, 'Piezômetro')], verbose_name='Tipo de instrumento')),
                ('install_height', models.FloatField(verbose_name='Cota instalação')),
                ('equation', models.FloatField(verbose_name='Equação')),
                ('attention_value', models.FloatField(verbose_name='Valor atenção')),
                ('id_ind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_industry_instruments', to='api.industry')),
            ],
        ),
    ]
